# Generated by Django 4.0.3 on 2022-05-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordstorage', '0002_alter_passwordcell_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordcell',
            name='service',
            field=models.CharField(db_index=True, max_length=13, verbose_name='Название приложения'),
        ),
        migrations.AlterField(
            model_name='passwordcell',
            name='user_password',
            field=models.CharField(max_length=128, verbose_name='Используемый пароль'),
        ),
    ]
