# Generated by Django 4.0.3 on 2022-05-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordstorage', '0004_alter_passwordcell_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordcell',
            name='user_password',
            field=models.CharField(max_length=1024, verbose_name='Используемый пароль'),
        ),
    ]
